### ISSUE TITLE
whoo

### ISSUE THREAD

**Issue by yourbask** [openwrtkitty/photonicat-ipks#1]
passwall显示不正常, tcp 和 udp 显示"未运行",希望您能抽空更新一下匹配光影猫固件的科学ipks

**Comment by do21** [comment]
同样的问题

**Comment by openwrtkitty** [comment]
好像插件编译出来就是这样，我再检查下。

**Comment by do21** [comment]
> 好像插件编译出来就是这样，我再检查下。

最新的1217版固件，外加昨天的包，还是显示【未运行】。

**Comment by do21** [comment]
> 好像插件编译出来就是这样，我再检查下。

最新的1217版固件，外加昨天的包，还是显示【未运行】。

**Comment by do21** [comment]
> 好像插件编译出来就是这样，我再检查下。

你好，问题我找到了
https://github.com/xiaorouji/openwrt-passwall/issues/2102
跟这个一样，把 /usr/bin/top 改名，新建一个link到/bin/busybox就好了。
是否考虑下次编译的时候不要用procps-ng了。

**Comment by do21** [comment]
> passwall显示不正常, tcp 和 udp 显示"未运行",希望您能抽空更新一下匹配光影猫固件的科学ipks

你可以暂时这样，ssh进到后台，执行
`root@photonicats:/# mv /usr/bin/top /usr/bin/top.old`
`root@photonicats:/# ln -s /bin/busybox /usr/bin/top`

**Comment by openwrtkitty** [comment]
Already fixed in new release.
