### ISSUE TITLE
希望适配R2304版本，希望添加mosdns

### ISSUE THREAD

**Issue by a757814283** [openwrtkitty/photonicat-ipks#11]
因为买的顶配版好像只能使用最新的固件，R2304版本的只能装上clash，但是好像不能正常使用，希望适配！
感觉mosdns和passwall非常般配，希望可以支持！

**Comment by kyc-88** [comment]
附议，希望适配mosdns，确实搭配passwall使用效果优秀

**Comment by secondline** [comment]
还有wireguard

**Comment by openwrtkitty** [comment]
mosdns will be included in next release.
