### ISSUE TITLE
kmod-tun dependency 

### ISSUE THREAD

**Issue by higgssinglet** [openwrtkitty/photonicat-ipks#2]
Just downloaded and installed science_net.tar.xz and wireguard.tar.xz.

1.  Not able to start Zerotier, when reinstall Zerotier, have kmod-tun dependency error.
2. After install wireguard, it does not show up on either service nor VPN.  When try to reinstall via software, also complains about kmod-tun dependency error.

Any instructions to solve these issue will be greatly appreciated.

**Comment by openwrtkitty** [comment]
noted, will test today.

**Comment by openwrtkitty** [comment]
kmod-tun is already installed by default with the system. Please show the error logs if any error occurs.
